name: Release to WordPress.org
on:
  push:
    tags:
      - "*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Deploy to WordPress repository
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: centrobill-payment-gateway
      - name: Create Github release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')